from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('logout/', views.logout_view, name='logout'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('worker-dashboard/', views.worker_dashboard, name='worker_dashboard'),
    path('create-request/', views.create_request, name='create_request'),
    path('edit-request/<int:pk>/', views.edit_request, name='edit_request'),
    path('close-request/<int:pk>/', views.close_request, name='close_request'),
    path('view-request/<int:pk>/', views.view_request, name='view_request'),
    path('update-money-delivered/', views.update_money_delivered, name='update_money_delivered'),
    path('cancel-request/<int:pk>/', views.cancel_request, name='cancel_request'),
    path('accept-request/<int:pk>/', views.accept_request, name='accept_request'),
    path('delete-request/<int:pk>/', views.delete_request, name='delete_request'),
    path('api/requests/', views.get_requests, name='api_requests'),
    path('api/worker-requests/', views.get_worker_requests, name='api_worker_requests'),
    path('api/workers/', views.get_workers, name='api_workers'),
    path('api/request-options/', views.get_request_options, name='api_request_options'),
    path('api/request-options/add/', views.add_request_option, name='api_request_option_add'),
    path('api/request-options/delete/', views.delete_request_option, name='api_request_option_delete'),
    path('api/cancel-amount-settings/', views.get_cancel_amount_settings, name='api_cancel_amount_settings'),
    path('api/cancel-amount-settings/update/', views.update_cancel_amount_settings, name='api_cancel_amount_settings_update'),
    path('api/worker-instruction/', views.api_worker_instruction, name='api_worker_instruction'),
    path('api/worker-instruction/update/', views.api_worker_instruction_update, name='api_worker_instruction_update'),
    path('upload-worker-instruction-image/', views.upload_worker_instruction_image, name='upload_worker_instruction_image'),
    path('api/documents/', views.get_documents, name='api_documents'),
    path('upload-document/', views.upload_document, name='upload_document'),
    path('delete-document/<int:pk>/', views.delete_document, name='delete_document'),
    path('delete-worker/<int:pk>/', views.delete_worker, name='delete_worker'),
    path('reopen-request/<int:pk>/', views.reopen_request, name='reopen_request'),
    path('generate-tg-code/', views.generate_tg_code, name='generate_tg_code'),
    path('generate-max-code/', views.generate_max_code, name='generate_max_code'),
    path('bind-messengers/', views.bind_messengers, name='bind_messengers'),
    path('update-worker-equipment-types/', views.update_worker_equipment_types, name='update_worker_equipment_types'),
    path('update-worker-percent/<int:pk>/', views.update_worker_percent, name='update_worker_percent'),
]