# Generated by Django 6.0.3 on 2026-03-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вид техники'),
        ),
    ]
