# Generated by Django 6.0.3 on 2026-03-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_request_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('contract', 'Договор'), ('receipt', 'Чек')], default='receipt', max_length=10, verbose_name='Тип фото'),
        ),
    ]
