# Generated by Django 6.0.3 on 2026-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_photo_photo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='deadline_days',
        ),
        migrations.AddField(
            model_name='request',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
