# Generated by Django 6.0.3 on 2026-03-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_request_deadline_days_request_deadline_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование детали')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена детали')),
                ('receipt_image', models.ImageField(upload_to='receipts/', verbose_name='Чек за деталь')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.request')),
            ],
        ),
    ]
