# Generated by Django 6.0.3 on 2026-03-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название детали')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='Чек за деталь')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='main.request')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
