# Generated by Django 6.0.3 on 2026-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_part_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='overdue_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина просрочки'),
        ),
    ]
