# Generated by Django 6.0.3 on 2026-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_request_overdue_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='prepayment_made',
            field=models.BooleanField(default=False, verbose_name='Предоплата внесена'),
        ),
    ]
