# Generated by Django 6.0.3 on 2026-03-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_request_prepayment_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Код из MAX'),
        ),
    ]
