# Generated by Django 6.0.3 on 2026-03-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_max_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код из MAX'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код из Telegram'),
        ),
    ]
