# Generated by Django 6.0.3 on 2026-03-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_profile_max_code_alter_profile_tg_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='worker_percent',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Процент рабочего от чистой прибыли'),
        ),
    ]
