# Generated by Django 6.0.3 on 2026-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_request_worker_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='prepayment_made',
        ),
        migrations.AddField(
            model_name='request',
            name='prepayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма предоплаты'),
        ),
    ]
